import pandas as pd
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.platypus import Table, TableStyle
from reportlab.lib import colors
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.base import MIMEBase
from email import encoders
import os
import qrcode # For QR code generation
from datetime import datetime
# Calculate Net Salary

def calculate_net_salary(employee_data):
    """Calculate Net Salary."""
    salary = float(employee_data.get('Salary', 0))
    allowance = float(employee_data.get('Allowances', 0))
    deduction = float(employee_data.get('Deductions', 0))
    return salary + allowance - deduction

# Generate Payslip PDF
def generate_payslip(employee_data, filename, logo_path=None, current_month=None):
    """Generate a single payslip PDF."""
    c = canvas.Canvas(filename, pagesize=letter)
    # Add company logo if provided
    if logo_path and os.path.exists(logo_path):
        c.drawImage(logo_path, 50, 740, width=100, height=50)
    # Header
    c.setFont("Helvetica-Bold", 16)
    c.drawString(200, 750, "PHONIX MEDIA PRO")
    c.setFont("Helvetica-Bold", 16)
    c.drawString(200, 730, "Employee Payslip")
    # Employee details
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, 700, f"Employee ID: {employee_data.get('EmployeeID', 'N/A')}")
    c.drawString(300, 700, f"Name: {employee_data.get('Name', 'N/A')}")
    # Date (current month/year)
    c.setFont("Helvetica", 10)
    c.drawString(400, 700, f"Month: {current_month}")
    # Salary breakdown
    net_salary = calculate_net_salary(employee_data)
    salary_table = [
        ['Component', 'Amount'],
        ['Salary', f"${float(employee_data.get('Salary', 0)):.2f}"],
        ['Allowance', f"${float(employee_data.get('Allowances', 0)):.2f}"],
        ['Deduction', f"${float(employee_data.get('Deductions', 0)):.2f}"],
        ['Net Salary', f"${net_salary:.2f}"]
    ]
    table = Table(salary_table, colWidths=[200, 150])
    table.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BACKGROUND', (0, 0), (-1, 0), colors.lightgrey),
        ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
        ('FONTSIZE', (0, 0), (-1, -1), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 6),
    ]))
    # Draw the table
    table.wrapOn(c, 400, 200)
    table.drawOn(c, 50, 550)
    # QR Code for Employee ID
    qr_code = qrcode.make(employee_data.get('EmployeeID', 'N/A'))
    qr_code_path = "qr_code.png"
    qr_code.save(qr_code_path)
    c.drawImage(qr_code_path, 450, 600, width=100, height=100)
    # Footer
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, 50, "PHONIX MEDIA PRO - Confidential Payslip")
    c.drawString(400, 50, "Generated by Payroll System")
    c.save()
    os.remove(qr_code_path)  # Clean up QR code image file

def send_email(pdf_filename, recipient_email, sender_email, sender_password):
    """Send an email with the PDF attached."""
    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = recipient_email
    msg['Subject'] = 'Your Employee Payslip'
    # Attach the PDF
    part = MIMEBase('application', 'octet-stream')
    with open(pdf_filename, 'rb') as file:
        part.set_payload(file.read())
    encoders.encode_base64(part)
    part.add_header('Content-Disposition', f'attachment; filename={os.path.basename(pdf_filename)}')
    msg.attach(part)
    # Send email
    with smtplib.SMTP('smtp.gmail.com', 587) as server:
        server.starttls()
        server.login(sender_email, sender_password)
        server.sendmail(sender_email, recipient_email, msg.as_string())
    print(f"📧 Payslip sent to {recipient_email}")

# Load employee data from Excel
excel_file = r"C:\Users\uncommonStudent\OneDrive\Desktop\selwyn python\employees.xlsx"
df = pd.read_excel(excel_file)
df.columns = df.columns.str.strip()  # Remove leading/trailing spaces
# Print out the actual column names for troubleshooting
print("Column names in the Excel file:", df.columns)
# Validate required columns
required_columns = {'EmployeeID', 'Name', 'Salary', 'Allowances', 'Deductions', 'Email'}
missing = required_columns - set(df.columns)
if missing:
    raise KeyError(f"Missing required columns in Excel file: {missing}")
# Output folder for PDFs
output_folder = os.path.join(os.path.dirname(excel_file), "payslips")
os.makedirs(output_folder, exist_ok=True)
# Optional: logo
logo_path = os.path.join(os.path.dirname(excel_file), "company_logo.png")
# Get current month
current_month = datetime.now().strftime("%B %Y")
# Email details (replace with your actual details)
sender_email = "your_email@gmail.com" # Your email address
sender_password = "app_password" # Your email password or app password
# Generate PDF and send via email
for _, row in df.iterrows():
    name_safe = str(row['Name']).strip().replace(' ', '_')
    pdf_filename = os.path.join(output_folder, f"{name_safe}_payslip.pdf")
    generate_payslip(row, pdf_filename, logo_path=logo_path, current_month=current_month)
    # Send email with the payslip
    if 'Email' in row:  # Check if the 'Email' column exists
        recipient_email = row['Email']  # The employee's email address from the Excel file
        send_email(pdf_filename, recipient_email, sender_email, sender_password)
    else:
        print(f"❌ Email not found for {row['Name']}")
print("✅ Payslips generated and sent successfully.")

def send_email(pdf_filename, recipient_email, sender_email, sender_password):
    """Send an email with the PDF attached."""
    try:
        # Create message
        msg = MIMEMultipart()
        msg['From'] = sender_email
        msg['To'] = recipient_email
        msg['Subject'] = 'Your Employee Payslip'
        
        # Attach the PDF
        with open(pdf_filename, 'rb') as file:
            part = MIMEBase('application', 'octet-stream')
            part.set_payload(file.read())
            encoders.encode_base64(part)
            part.add_header('Content-Disposition', 
                          f'attachment; filename={os.path.basename(pdf_filename)}')
            msg.attach(part)
        
        # Send email with detailed logging
        with smtplib.SMTP('smtp.gmail.com', 587) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            
            # Try to send the email
            try:
                server.sendmail(sender_email, recipient_email, msg.as_string())
                print(f"✅ Email sent successfully to {recipient_email}")
                return True
            except smtplib.SMTPRecipientsRefused as e:
                print(f"❌ Error: Email address {recipient_email} was refused")
                print(f"Error details: {e}")
                return False
            except smtplib.SMTPAuthenticationError as e:
                print(f"❌ Authentication failed for {sender_email}")
                print(f"Error details: {e}")
                return False
            except smtplib.SMTPException as e:
                print(f"❌ SMTP error sending to {recipient_email}")
                print(f"Error details: {e}")
                return False
            except Exception as e:
                print(f"❌ Unexpected error sending to {recipient_email}")
                print(f"Error details: {e}")
                return False
                
    except Exception as e:
        print(f"❌ Failed to prepare email for {recipient_email}")
        print(f"Error details: {e}")
        return False
    
    # Generate PDF and send via email
success_count = 0
total_emails = 0

for _, row in df.iterrows():
    name_safe = str(row['Name']).strip().replace(' ', '_')
    pdf_filename = os.path.join(output_folder, f"{name_safe}_payslip.pdf")
    
    # Generate payslip
    generate_payslip(row, pdf_filename, logo_path=logo_path, current_month=current_month)
    
    # Try to send email
    if 'Email' in row:
        total_emails += 1
        recipient_email = row['Email']
        if send_email(pdf_filename, recipient_email, sender_email, sender_password):
            success_count += 1
        else:
            print(f"Failed to send email to {recipient_email}")

# Print summary
print(f"\nEmail Summary:")
print(f"Total emails attempted: {total_emails}")
print(f"Successful deliveries: {success_count}")
print(f"Failed deliveries: {total_emails - success_count}")

